### ISSUE TITLE
What assets are being used

### ISSUE THREAD

**Issue by amatiasq** [Vinorcola/CityBuilderEngine#17]
Hi! I was wondering how did you get the original assets.

I would like to participate on this project but I'm not very good with C++ and would make a mess out of it. I'm interested on building a WebAssembly version playable in the browser, not sure yet what language to use.

Anyway I was wondering

- Did you re-do the assets?
- Are you allowed to use them?
- Can I use them?

**Comment by Vinorcola** [comment]
Hi,

- I used this tool to extract the assets: https://github.com/bvschaik/citybuilding-tools I enhanced it to fit my uses : https://github.com/Vinorcola/citybuilding-tools
- I am allowed to use them because I have bough the original game. I, however, am not allowed to distribute them. Now, I'm just building the "game engine" and the images are just used to give a display, but as you may have seen, the display is not optimal and I don't intend to enhance it a lot since I'd like to focus on game logic.
- You can use Bianca Schaik's tools (or mine) to extract the assets of the game if you have the original :)

**Comment by amatiasq** [comment]
Excellent, thank you for such a clear answer 👍

**Comment by MartiniDry** [comment]
Hello, @Vinorcola , if I understand well we won't be allowed to see any remastered version of the game?

**Comment by Vinorcola** [comment]
Not without authorization from Activision, which are I belive, the "legal" owner of Zeus, Pharaoh, etc.

A Pharaoh remastered version is being made by Triskell Interactive : https://store.steampowered.com/app/1351080/Pharaoh_A_New_Era/
They had negociations with Activision to be allowed to do it (and Activitsion certainly taking a part of the profits).
